"""Check every camera bookmark and render small previews or selected final stills.

Uses the saved scene; no geometry or presentation is regenerated by this script.
"""

import contextlib
import io
import json
import os
import sys
import time

import bpy
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "homespec", "blender"))
import frames  # noqa: E402
import session  # noqa: E402


def checked(check, *args):
    """Treat the CLI frame checks' ERROR reports as verification failures."""
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        check(*args)
    report = output.getvalue()
    if report:
        print(report, end="", flush=True)
    errors = [line for line in report.splitlines() if line.startswith("ERROR ")]
    if errors:
        raise RuntimeError("\n".join(errors))


args = sys.argv[sys.argv.index("--") + 1 :]
out = os.path.abspath(args[0])
quality = args[1] if len(args) > 1 else "preview"
scn = bpy.context.scene
session.scn = scn
points = json.loads(scn["flechon_waypoints"])
cam = scn.camera
cam.animation_data_clear()
scn.animation_data_clear()
scn.render.engine = "CYCLES"
scn.cycles.samples = 24 if quality == "preview" else 192
scn.cycles.adaptive_threshold = 0.12 if quality == "preview" else 0.035
scn.cycles.use_denoising = True
scn.render.resolution_x = 960 if quality == "preview" else 1920
scn.render.resolution_y = 600 if quality == "preview" else 1200
scn.render.resolution_percentage = 100
prefs = bpy.context.preferences.addons["cycles"].preferences
prefs.compute_device_type = "METAL"
prefs.get_devices()
for d in prefs.devices:
    d.use = d.type == "METAL"
scn.cycles.device = "GPU"
selected = set(map(int, args[2].split(","))) if len(args) > 2 else None
if selected is not None and (not selected or not selected.issubset(range(len(points)))):
    raise ValueError(f"Requested viewpoint indices must be between 0 and {len(points) - 1}: {selected}")
gallery = os.path.join(out, "previews" if quality == "preview" else "gallery")
os.makedirs(gallery, exist_ok=True)
for i, p in enumerate(points):
    if selected is not None and i not in selected:
        continue
    cam.location = p["location"]
    cam.rotation_euler = Vector(p["look"]).to_track_quat("-Z", "Y").to_euler()
    scn.view_settings.exposure = p.get("exposure", 0)
    bpy.context.view_layer.update()
    checked(frames.check_camera)
    slug = "".join(c if c.isalnum() else "-" for c in p["name"].lower()).strip("-")
    scn.render.filepath = os.path.join(gallery, f"{i + 1:02d}-{slug}.png")
    start = time.time()
    bpy.ops.render.render(write_still=True)
    checked(frames.check_frame, scn.render.filepath)
    print("VERIFIED VIEW", i, p["name"], scn.render.filepath, round(time.time() - start, 1), "seconds", flush=True)
print("ALL REQUESTED VIEWS VERIFIED", flush=True)
