"""Requirements as an IDS file, validated against the exported IFC.

IDS (Information Delivery Specification) is buildingSMART's format for
machine-checkable requirements on an IFC model. Geometry rules live in
:mod:`homespec.checks.residential`; property and classification rules live
here, where an architect's tool can run the same file.
"""
from __future__ import annotations

import ifcopenshell
from ifctester import ids

from .base import Result


def specification(project: str) -> ids.Ids:
    spec = ids.Ids(title=f"{project} requirements", description="Generated by homespec")
    spec.specifications.append(_spec("Walls declare whether they are external", "IFCWALL", "Pset_WallCommon", "IsExternal", "IfcBoolean"))
    spec.specifications.append(_spec("Doors declare whether they are external", "IFCDOOR", "Pset_DoorCommon", "IsExternal", "IfcBoolean"))
    spec.specifications.append(_spec("Windows declare whether they are external", "IFCWINDOW", "Pset_WindowCommon", "IsExternal", "IfcBoolean"))
    for cls in ("IFCWALL", "IFCDOOR", "IFCWINDOW", "IFCSLAB", "IFCBEAM", "IFCFURNITURE", "IFCLIGHTFIXTURE", "IFCOUTLET"):
        spec.specifications.append(_spec(f"{cls.title()} carries its homespec id and tags", cls, "HouseSpec", "tags", "IfcLabel"))
    return spec


def _spec(name: str, entity: str, pset: str, prop: str, dtype: str) -> ids.Specification:
    s = ids.Specification(name=name, ifcVersion=["IFC4"])
    s.applicability.append(ids.Entity(name=entity))
    s.requirements.append(ids.Property(baseName=prop, propertySet=pset, dataType=dtype, cardinality="required"))
    return s


def write(project: str, path: str) -> str:
    specification(project).to_xml(path)
    return path


def validate(project: str, ifc_path: str) -> list[Result]:
    """Run the IDS against the IFC; one :class:`Result` per specification."""
    spec = specification(project)
    model = ifcopenshell.open(ifc_path)
    spec.validate(model)
    out: list[Result] = []
    for s in spec.specifications:
        applicable = len(getattr(s, "applicable_entities", []) or [])
        failed = len(getattr(s, "failed_entities", []) or [])
        ok = bool(getattr(s, "status", failed == 0))
        out.append(Result(rule="ids", target=s.name, ok=ok, value=f"{applicable - failed}/{applicable} pass", limit="all", clause="IDS 1.0"))
    return out
